language: c
env:
  - BD=esp8266:esp8266:nodemcuv2:CpuFrequency=80,FlashSize=4M3M
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/NodeMCU_weather_display
# boards manager not working on 1.6.7 - 1.6.8
  - arduino --pref "boardsmanager.additional.urls=https://github.com/esp8266/Arduino/releases/download/2.1.0/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266
  - arduino --board $BD --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
# install lib
  - git clone https://github.com/adafruit/Adafruit_Sensor /usr/local/share/arduino/libraries/Adafruit_Sensor
# - git clone https://github.com/adafruit/DHT-sensor-library /usr/local/share/arduino/libraries/DHT-sensor-library
  - git clone https://github.com/squix78/esp8266-oled-ssd1306 /usr/local/share/arduino/libraries/esp8266-oled-ssd1306
  - git clone https://github.com/squix78/esp8266-weather-station /usr/local/share/arduino/libraries/esp8266-weather-station
  - git clone https://github.com/squix78/json-streaming-parser /usr/local/share/arduino/libraries/json-streaming-parser

script:
  - "echo $PWD"
  - "echo $HOME"
  - arduino --verify --board $BD $PWD/weather_station_firmware/weather_station_firmware.ino

notifications:
  email:
    on_success: change
    on_failure: change
